name: macos-build

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: chown /usr/local/eda
      run: |
        sudo mkdir /usr/local/eda
        sudo chown $(whoami) /usr/local/eda

    - name: Cache tcl/tk
      id: cache-tcltk
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-tcltk
        path: |
          /usr/local/eda/tcl-tk

    - name: Cache assets
      id: cache-eda
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-eda
        path: |
          /usr/local/eda

    - name: TCL/TK
      if: steps.cache-tcltk.outputs.cache-hit != 'true'
      run: make tcl_compile tcl_install tk_compile tk_install

    - name: homebrew
      run: make requirements

    - name: Cache netgen
      id: cache-netgen
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-netgen
        path: |
          /usr/local/eda

    - name: Netgen
      if: steps.cache-netgen.outputs.cache-hit != 'true'
      run: |
        make netgen_compile
        sudo make netgen_install

    - name: Cache magic
      id: cache-magic
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-magic
        path: |
          /usr/local/eda
