name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tcltk:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: chown /usr/local/eda
      run: |
        sudo mkdir /usr/local/eda
        sudo chown $(whoami) /usr/local/eda

    - name: Cache tcl/tk
      id: cache-tcltk
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-tcltk
        path: |
          /usr/local/eda/tcl-tk

    - name: TCL/TK
      if: steps.${{ runner.os }}-tcltk.outputs.cache-hit != 'true'
      run: make tcl_compile tcl_install tk_compile tk_install

  prepare:
    runs-on: macos-latest
    steps:
      - name: homebrew
        step: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install XQuartz on macOS
        if: runner.os == 'macOS'
        run: brew install xquartz --cask

  netgen:
    runs-on: macos-latest
    needs: tcltk
    steps:
    - name: Netgen
      run: make netgen_compile netgen_install

  ngspice:
    runs-on: macos-latest
    needs: tcltk
    steps:
    - name: Ngspice
      run: make ngspice_compile ngspice_install

  magic:
    runs-on: macos-latest
    needs: tcltk
    steps:
    - name: Magic
      run: make magic_compile magic_install

  xschem:
    runs-on: macos-latest
    needs: tcltk
    steps:
    - name: Xschem
      run: make xschem_compile xschem_install
