name: macos-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: chown /usr/local/eda
      run: |
        sudo mkdir /usr/local/eda
        sudo chown $(whoami) /usr/local/eda

    - name: Cache tcl/tk
      id: cache-tcltk
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-tcltk
        path: |
          /usr/local/eda/tcl-tk

    - name: Cache assets
      id: cache-eda
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-eda
        path: |
          /usr/local/eda

    - name: TCL/TK
      if: steps.cache-tcltk.outputs.cache-hit != 'true'
      run: make tcl_compile tcl_install tk_compile tk_install

    - name: homebrew
      run: |
        brew list
        brew install xquartz --cask
        brew install libxpm
        brew install bison
        brew install readline
        brew install libomp
        brew install automake
        brew install glib
        brew install libxaw
        brew install libtool
        brew install libx11

    - name: Ngspice
      run: make ngspice_compile ngspice_install

    - name: Netgen
      run: make netgen_compile netgen_install

    - name: Magic
      run: make magic_compile magic_install

    - name: Xschem
      run: make xschem_compile xschem_install

    - name: Make tar
      run: |
        tar cfz docs/assets/eda-macos-12.tar.gz /usr/local/eda

    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./docs/
        destination: ./_site
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1

# Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
