name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: TCL/TK
      run: make tcl_compile tcl_install tk_compile tk_install

    - name: Netgen
      run: make netgen_compile netgen_install

    - name: Ngspice
      run: make ngspice_compile ngspice_install

    - name: Magic
      run: make magic_compile magic_install

    - name: Xschem
      run: make xschem_compile xschem_install
