name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: TCL/TK
      run: make tcl_compile tcl_install tk_compile tk_install
    - name: package
      run: tar cfz tcl-tk.tar.gz /usr/local/opt2/tcl-tk
    - uses: actions/upload-artifact@v3
      with:
        name: tcltk
        path: tcl-tk.tar.gz
