name: TCL/TK CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  #workflow_call

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache tcl/tk
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/opt2/tcl-tk
    - name: TCL/TK
      run: make tcl_compile tcl_install tk_compile tk_install
