name: TCL/TK CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache tcl/tk
      id: cache-tcltk

      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-tcltk
        path: |
          /usr/local/opt2/tcl-tk
    - name: TCL/TK
      run: make tcl_compile tcl_install tk_compile tk_install
